let target = {
  JOIN_PAYMENT_FORM_TX_BROADCAST_PENDING: 'PAYMENT.JOIN_PAYMENT_FORM_TX_BROADCAST_PENDING',
  JOIN_PAYMENT_FORM_TX_BROADCAST_FULFILLED: 'PAYMENT.JOIN_PAYMENT_FORM_TX_BROADCAST_FULFILLED',
  JOIN_PAYMENT_FORM_TX_BROADCAST_REJECTED: 'PAYMENT.JOIN_PAYMENT_FORM_TX_BROADCAST_REJECTED',
  JOIN_PAYMENT_ACCOUNT_SELECTED: 'PAYMENT.JOIN_PAYMENT_ACCOUNT_SELECTED',
  JOIN_PAYMENT_NAME_SPECIFIED: 'PAYMENT.JOIN_PAYMENT_NAME_SPECIFIED',
  JOIN_PAYMENT_GAS_SPECIFIED: 'PAYMENT.JOIN_PAYMENT_GAS_SPECIFIED',
  JOIN_PAYMENT_GAS_PRICE_SPECIFIED: 'PAYMENT.JOIN_PAYMENT_GAS_PRICE_SPECIFIED',
  JOIN_PAYMENT_ERROR_THREW: 'PAYMENT.JOIN_PAYMENT_ERROR_THREW',
  JOIN_PAYMENT_EMPTIED: 'PAYMENT.JOIN_PAYMENT_EMPTIED',
}
let handler = {
  get: (target, key) => {
    if (target.hasOwnProperty(key)) return target[key];
    else throw new Error(`Fired a wrong actionname: ${key}. Available Actions: ${Object.keys(target)}`);
  }
}
const proxy = new Proxy(target, handler)
export default proxy